[package]
name = "tun"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = ["yamakaky"]

[dependencies]
bitflags = "0.7"
error-chain = "0.7"
ioctl = "0.3"
libc = "0.2"
tokio-core = "0.1"
mio = "0.6.1"

[dev-dependencies]
futures = "*"
